### PR TITLE
Jack categories

### PR DESCRIPTION
**Pull request by laurieskelly**
@GregoryBL @DanielJPark @kmbradshaw 
made 12 jack-related categories in seeds.rb. if you like 'em, merge 'em!

### CODE REVIEW

**Comment by GregoryBL** [comment]
Dunno who the fast food spokesman is, but love it.

**Comment by GregoryBL** [comment]
@laurieskelly maybe remove/comment everything else? This way we can seed the live one with categories without adding the other stuff.

**Comment by laurieskelly** [comment]
@GregoryBL 
sure thing, one sec

**Comment by laurieskelly** [comment]
@GregoryBL good to go

**Pull request merged**
