### PR TITLE
Homepage css / user_spec

### PR DESCRIPTION
**Pull request by kmbradshaw**

### CODE REVIEW

**Comment by laurieskelly** [comment]
@kmbradshaw pull master and merge master into your branch to resolve conflicts

**Comment by kmbradshaw** [comment]
merge conflicts dealt with - merge away if you approve @DanielJPark @laurieskelly @GregoryBL

**Comment by kmbradshaw** [comment]
should mention - the floats (aka columns - CSS columns just aren't universally accepted yet) will not look pretty without 12 or so categories, something to keep in mind when we are finalizing seeds

**Comment by laurieskelly** [comment]
looks good, merging

**Pull request merged**
